name: smart_auction
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  agora_rtc_engine: ^6.3.1
  agora_uikit: ^1.3.10
  awesome_card: ^1.1.7
  banner_carousel: ^1.2.1
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.3
  conditional_builder_null_safety: ^0.0.6
  contained_tab_bar_view: ^0.8.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.1
  dropdown_button2: ^2.3.9
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_colorpicker: null
  flutter_holo_date_picker: ^1.1.3
  flutter_rating_stars: ^1.0.3+4
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  flutter_swipe_action_cell: ^3.1.3
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  intl: null
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  slide_countdown: ^1.3.5
  smooth_page_indicator: ^1.1.0
  top_snackbar_flutter: ^3.1.0
  tuple: ^2.0.2
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/Icons/
    - assets/Images/

  fonts:
    - family: Inter700
      fonts:
        - asset: assets/Fonts/Inter-Bold.ttf
    - family: Inter500
      fonts:
        - asset: assets/Fonts/Inter-Medium.ttf
    - family: Inter400
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
    - family: Inter600
      fonts:
        - asset: assets/Fonts/Inter-SemiBold.ttf
    - family: Poppins700
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
    - family: Poppins500
      fonts:
        - asset: assets/Fonts/Poppins-Medium.ttf
    - family: Poppins400
      fonts:
        - asset: assets/Fonts/Poppins-Regular.ttf
