// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4U61F7hFWQ89TRqlz4GNLWKuRaFQoFWQ',
    appId: '1:359104392455:android:fa858b185bda1c5059a9a2',
    messagingSenderId: '359104392455',
    projectId: 'smart-trade-auction-pluse',
    storageBucket: 'smart-trade-auction-pluse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpII4d_3r2n0wv3Ia2FxoBTQtY8YrF_60',
    appId: '1:359104392455:ios:eb34b541790e6f1a59a9a2',
    messagingSenderId: '359104392455',
    projectId: 'smart-trade-auction-pluse',
    storageBucket: 'smart-trade-auction-pluse.appspot.com',
    iosBundleId: 'com.example.smartAuction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpII4d_3r2n0wv3Ia2FxoBTQtY8YrF_60',
    appId: '1:359104392455:ios:eb34b541790e6f1a59a9a2',
    messagingSenderId: '359104392455',
    projectId: 'smart-trade-auction-pluse',
    storageBucket: 'smart-trade-auction-pluse.appspot.com',
    iosBundleId: 'com.example.smartAuction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIg8yIORNdqQiaaZJ6timjcDin6ERd_sg',
    appId: '1:359104392455:web:97d2a85c06b6aafe59a9a2',
    messagingSenderId: '359104392455',
    projectId: 'smart-trade-auction-pluse',
    authDomain: 'smart-trade-auction-pluse.firebaseapp.com',
    storageBucket: 'smart-trade-auction-pluse.appspot.com',
    measurementId: 'G-CFNX559R8F',
  );
}
